version: "2.2"
services:
  php-5.5:
    image: maadamaceno/damabox_php5.5:latest
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP55_CONFIG_DIR:-./config/php/5.5}:/usr/local/etc/php
    networks:
      - connect

  php-5.6:
    image: maadamaceno/damabox_php5.6:latest
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP56_CONFIG_DIR:-./config/php/5.6}:/usr/local/etc/php
    networks:
      - connect

  php-7.0:
    image: maadamaceno/damabox_php7.0:latest
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP70_CONFIG_DIR:-./config/php/7.0}:/usr/local/etc/php
    networks:
      - connect

  php-7.1:
    image: maadamaceno/damabox_php7.1:latest
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP71_CONFIG_DIR:-./config/php/7.1}:/usr/local/etc/php
    networks:
      - connect

  nginx:
    image: maadamaceno/damabox_nginx:latest
    restart: always
    ports:
     - "${HTTP_PORT:-80}:80"
    volumes:
     - ${NGINX_CONFIG_DIR:-./config/nginx}:/etc/nginx/conf
     - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
     - ${PROJECT_DIR:-./data/www}:/app
    networks:
      - connect

  mysql:
    image: ${MYSQL_TYPE:-mysql}:${MYSQL_VERSION:-5.7}
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ${MYSQL_DATADIR:-./data/databases/mysql}/${MYSQL_VERSION:-5.7}:/var/lib/mysql
      - ${DB_CONFIG_DIR:-./config/db}/${MYSQL_TYPE:-mysql}:/etc/mysql/conf.d
    networks:
      - connect

  firebird:
    image: maadamaceno/damabox_firebird:latest
    restart: always
    environment:
      - FIREBIRD_USER=${FIREBIRD_ROOT_USER:-sysdba}
      - FIREBIRD_PASSWORD=${FIREBIRD_ROOT_PASSWORD:-masterkey}
      - ISC_PASSWORD=${FIREBIRD_ROOT_PASSWORD:-masterkey}
    ports:
      - "${FIREBIRD_PORT:-3050}:3050"
    volumes:
      - ${FIREBIRD_DATADIR:-./data/databases/firebird}:/databases
    networks:
      - connect

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    restart: always
    ports:
      - "${ES_PORT:-9200}:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ${ES_DATADIR:-./config/elasticsearch}:/usr/share/elasticsearch/config
    mem_limit: 1g
    cpu_count: 1
    cpu_percent: 10
    networks:
      - connect

networks:
  connect:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: 10.5.0.0/16
         ip_range: 10.5.0.0/24
         gateway: 10.5.0.1
